"""CLI command: `aegis init` — generate a starter aegis.yaml."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

app = typer.Typer(name="init", invoke_without_command=True, help="Generate a starter aegis.yaml.")
_console = Console()
_err_console = Console(stderr=True, style="bold red")

_DEFAULT_OUTPUT = Path("aegis.yaml")

# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# aegis.yaml — generated by `aegis init`
# Run `aegis config validate aegis.yaml` to validate this file.
# Run `aegis policy lint aegis.yaml` to check policy references.

# ── Providers ─────────────────────────────────────────────────────────────
# Uncomment and configure at least one provider before serving requests.
#
# providers:
#   my_provider:
#     type: openai_compatible
#     base_url: http://localhost:11434/v1
#     model: llama3
#     api_key: secret://env/MY_API_KEY#value

# ── Guardrails ────────────────────────────────────────────────────────────
# The PII guard is enabled by default (requires aegis-pack-pii[pii]).
# Add more guards from available packs below.

guardrails:
  pii:
    pack: aegis_pack_pii
    mode: mask

  # llm_guard:
  #   pack: aegis_pack_llm_guard
  #   scanners: [PromptInjection]
  #   threshold: 0.8

  # residency:
  #   pack: aegis_pack_residency
  #   region: us

# ── Pipeline ──────────────────────────────────────────────────────────────
# Guardrail names listed here must match keys in the guardrails section above.

pipeline:
  ingress: [pii]
  # tool_result: [pii]
  # egress: []   # note: non-incremental egress guards disable true-streaming

# ── Routes ────────────────────────────────────────────────────────────────
# Uncomment and configure after adding a provider above.
#
# routes:
#   default:
#     provider: my_provider
#     model: llama3

# ── Auth ──────────────────────────────────────────────────────────────────
# Change to `type: api_key` and use `aegis keys create` for production.

auth:
  type: none
"""


# ---------------------------------------------------------------------------
# Public helper for tests
# ---------------------------------------------------------------------------


def write_init_yaml(output: Path, force: bool = False) -> None:
    """Write the starter aegis.yaml to *output*.

    Raises:
        FileExistsError: If *output* exists and *force* is False.
    """
    if output.exists() and not force:
        raise FileExistsError(
            f"{output} already exists. Use --force to overwrite."
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_TEMPLATE)


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


@app.callback(invoke_without_command=True)
def init(
    output: Annotated[
        Path,
        typer.Option("--output", "-o", help="Output path for aegis.yaml."),
    ] = _DEFAULT_OUTPUT,
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Overwrite existing file."),
    ] = False,
) -> None:
    """Generate a starter aegis.yaml with PII guarding enabled."""
    try:
        write_init_yaml(output, force=force)
    except FileExistsError as exc:
        _err_console.print(str(exc))
        raise typer.Exit(1) from exc

    _console.print(f"[green]Created[/green] {output}")
    _console.print("  Validate: [cyan]aegis config validate aegis.yaml[/cyan]")
    _console.print("  Lint:     [cyan]aegis policy lint aegis.yaml[/cyan]")
