"""RAG contracts: Doc, VectorStoreProvider, EmbeddingProvider (PROJECT_SPEC §4 D3)."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable


@dataclass
class Doc:
    """A document for indexing or retrieval.

    Attributes:
        text: Raw document text.
        metadata: Arbitrary key/value metadata (source path, page number, etc.).
        id: Optional stable identifier; generated by the store if *None*.
        embedding: Pre-computed embedding vector; *None* until the store embeds it.
    """

    text: str
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str | None = None
    embedding: list[float] | None = None


@runtime_checkable
class EmbeddingProvider(Protocol):
    """Produces dense embedding vectors from text (PROJECT_SPEC §4 D3).

    Implementations must be async-first.  A sync fallback is acceptable only
    in CLI wrappers; all pipeline paths call ``await embed(...)``.
    """

    name: str

    async def embed(self, texts: list[str]) -> list[list[float]]:
        """Return one embedding vector per input text."""
        ...


@runtime_checkable
class VectorStoreProvider(Protocol):
    """Persists and retrieves document vectors (PROJECT_SPEC §4 D3).

    The caller is responsible for embedding: ``add`` receives plain
    :class:`Doc` objects and the implementation must embed them; ``query``
    receives a *pre-computed* vector produced by an :class:`EmbeddingProvider`.
    """

    async def add(self, docs: list[Doc], namespace: str) -> None:
        """Embed and index *docs* in *namespace*."""
        ...

    async def query(
        self, vector: list[float], namespace: str, k: int
    ) -> list[Doc]:
        """Return up to *k* :class:`Doc` objects closest to *vector* in *namespace*."""
        ...
